import React, { useState } from 'react';
import {
  Check,
  Copy,
  Flame,
  GitBranch,
  Lightbulb,
  Loader2,
  RefreshCw,
  Terminal,
} from 'lucide-react';
import { Card } from './ui/Card';
import { Badge } from './ui/Badge';
import { Button } from './ui/Button';
import type { BrutalityLevel } from '../types';

interface RoastCardProps {
  username?: string;
  roast: string;
  explanation: string;
  brutality: BrutalityLevel;
  aiAvailable: boolean;
  groundingRepos?: string[];
  comicDevice?: string | null;
  onRetryAi?: () => void;
  onBrutalityChange?: (newBrutality: BrutalityLevel) => void;
  isSwitchingBrutality?: boolean;
  onRegenerateRoast?: () => void;
  isRegeneratingRoast?: boolean;
  roastVariant?: number;
}

const BRUTALITY_MODES: {
  id: BrutalityLevel;
  label: string;
  icon: string;
  descriptor: string;
}[] = [
  {
    id: 'professional',
    label: 'Professional',
    icon: '👔',
    descriptor: 'Staff+ Leader: diplomatic & dry wit',
  },
  {
    id: 'honest',
    label: 'Honest',
    icon: '🎯',
    descriptor: 'Candid Peer: direct & pragmatic',
  },
  {
    id: 'brutal',
    label: 'Brutal',
    icon: '🔥',
    descriptor: 'Roastmaster: sharp & comedic',
  },
];

export const RoastCard: React.FC<RoastCardProps> = ({
  username = '',
  roast,
  explanation,
  brutality,
  aiAvailable,
  groundingRepos = [],
  comicDevice,
  onRetryAi,
  onBrutalityChange,
  isSwitchingBrutality = false,
  onRegenerateRoast,
  isRegeneratingRoast = false,
  roastVariant = 0,
}) => {
  const [copied, setCopied] = useState(false);

  const handleCopyRoast = async () => {
    try {
      const shareText = `🔥 GitRoast for @${username || 'developer'}:\n"${roast}"\n\nFix: ${explanation}\n\nGenerated by GitRoast`;
      await navigator.clipboard.writeText(shareText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2200);
    } catch {
      setCopied(false);
    }
  };

  const activeMode = BRUTALITY_MODES.find((b) => b.id === brutality) || BRUTALITY_MODES[1];

  if (!aiAvailable) {
    return (
      <Card variant="default" padding="lg" className="h-full flex flex-col justify-between border-dashed">
        <div>
          <div className="flex items-center justify-between mb-3">
            <div className="flex items-center gap-2">
              <div className="w-7 h-7 rounded-md bg-roast/10 text-roast flex items-center justify-center">
                <Flame className="w-4 h-4" />
              </div>
              <h3 className="text-base font-bold text-text-primary">AI Roast & Analysis</h3>
            </div>
            <Badge variant="outline" size="sm">
              Temporarily Offline
            </Badge>
          </div>
          <p className="text-xs sm:text-sm text-text-secondary mb-4 leading-relaxed">
            Deterministic code scores are active, but the AI roast generator was temporarily unreachable.
          </p>
        </div>

        {onRetryAi && (
          <Button
            type="button"
            variant="secondary"
            size="sm"
            onClick={onRetryAi}
            leftIcon={<RefreshCw className="w-3.5 h-3.5" />}
            className="self-start text-xs"
          >
            Retry AI Synthesis
          </Button>
        )}
      </Card>
    );
  }

  const isBrutal = brutality === 'brutal';

  return (
    <Card
      variant="default"
      padding="lg"
      className={`h-full flex flex-col justify-between relative overflow-hidden transition-all duration-300 ${
        isBrutal
          ? 'border-roast/40 bg-gradient-to-br from-surface via-[#181115] to-[#1F0E13]'
          : 'border-border bg-surface'
      }`}
    >
      {/* Ambient background glow */}
      <div
        className={`absolute -right-20 -top-20 w-64 h-64 rounded-full blur-3xl pointer-events-none opacity-20 ${
          isBrutal ? 'bg-roast' : 'bg-accent'
        }`}
      />

      <div>
        {/* Header Bar: Title + Tone Selector + Actions */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-3">
          <div className="flex items-center gap-2">
            <div
              className={`w-7 h-7 rounded-md flex items-center justify-center shadow-subtle ${
                isBrutal ? 'bg-roast/20 text-roast' : 'bg-accent/20 text-accent-light'
              }`}
            >
              <Flame className="w-4 h-4" />
            </div>
            <div>
              <h2 className="text-base font-bold text-text-primary tracking-tight">
                {isBrutal ? 'The Brutal Roast' : 'Career Diagnostic Roast'}
              </h2>
            </div>
            {(isSwitchingBrutality || isRegeneratingRoast) && (
              <Loader2 className="w-3.5 h-3.5 text-accent animate-spin ml-1" />
            )}
          </div>

          <div className="flex flex-wrap items-center gap-2 self-start sm:self-auto">
            {/* Tone / Brutality Switcher */}
            {onBrutalityChange && (
              <div className="flex gap-1 bg-bg/80 p-0.5 rounded-lg border border-border/80">
                {BRUTALITY_MODES.map((b) => {
                  const isSelected = brutality === b.id;
                  return (
                    <button
                      key={b.id}
                      type="button"
                      disabled={isSwitchingBrutality || isRegeneratingRoast}
                      onClick={() => onBrutalityChange(b.id)}
                      className={`text-[11px] font-mono px-2 py-1 rounded-md transition-all flex items-center gap-1 ${
                        isSelected
                          ? b.id === 'brutal'
                            ? 'bg-roast text-white font-semibold shadow-sm'
                            : 'bg-accent text-white font-semibold shadow-sm'
                          : 'text-text-muted hover:text-text-primary'
                      }`}
                      title={b.descriptor}
                    >
                      <span>{b.icon}</span>
                      <span className="hidden xs:inline">{b.label}</span>
                    </button>
                  );
                })}
              </div>
            )}

            {/* Regenerate Roast Button */}
            {onRegenerateRoast && (
              <Button
                type="button"
                variant="secondary"
                size="sm"
                onClick={onRegenerateRoast}
                disabled={isRegeneratingRoast || isSwitchingBrutality}
                leftIcon={
                  isRegeneratingRoast ? (
                    <Loader2 className="w-3.5 h-3.5 animate-spin text-accent" />
                  ) : (
                    <RefreshCw className="w-3.5 h-3.5 text-text-muted hover:text-text-primary transition-transform group-hover:rotate-180" />
                  )
                }
                className="text-xs px-2.5 py-1 h-7 font-mono"
                title="Regenerate roast with different angles and comic device"
              >
                {isRegeneratingRoast ? 'Generating...' : roastVariant > 0 ? `Re-roll (v${roastVariant + 1})` : 'Re-roll'}
              </Button>
            )}

            {/* Copy / Share Button */}
            <Button
              type="button"
              variant="secondary"
              size="sm"
              onClick={handleCopyRoast}
              leftIcon={copied ? <Check className="w-3.5 h-3.5 text-score-success" /> : <Copy className="w-3.5 h-3.5" />}
              className="text-xs px-2.5 py-1 h-7"
              title="Copy roast to clipboard"
            >
              {copied ? 'Copied!' : 'Share'}
            </Button>
          </div>
        </div>

        {/* Active Tone Sub-label */}
        <div className="flex items-center gap-2 mb-3 text-[11px] font-mono text-text-muted">
          <span className="text-text-secondary font-semibold">Voice:</span>
          <span>{activeMode.descriptor}</span>
          {comicDevice && (
            <span className="inline-flex items-center gap-1 ml-auto text-[10px] bg-surface-elevated px-2 py-0.5 rounded border border-border text-text-secondary">
              <Terminal className="w-3 h-3 text-accent" />
              <span>Format: {comicDevice}</span>
            </span>
          )}
        </div>

        {/* The Signature Roast Quote */}
        <blockquote className="relative my-3 pl-4 border-l-2 border-roast/90 text-base sm:text-lg font-medium text-text-primary italic leading-relaxed tracking-normal font-sans">
          "{roast}"
        </blockquote>

        {/* Evidence Grounding Line */}
        {groundingRepos && groundingRepos.length > 0 && (
          <div className="my-3 flex flex-wrap items-center gap-1.5 text-xs text-text-muted font-mono">
            <span className="inline-flex items-center gap-1 text-[11px] text-text-secondary">
              <GitBranch className="w-3 h-3 text-accent-light" />
              Grounded in:
            </span>
            {groundingRepos.map((repoName) => (
              <span
                key={repoName}
                className="inline-flex items-center px-1.5 py-0.5 rounded bg-surface-elevated/80 border border-border/80 text-[11px] text-text-primary font-medium"
              >
                {repoName}
              </span>
            ))}
          </div>
        )}
      </div>

      {/* Strategic Hiring Manager Takeaway */}
      {explanation && (
        <div className="mt-3 pt-3.5 border-t border-border/60 bg-bg/60 rounded-xl p-3.5 flex items-start gap-2.5">
          <div className="w-6 h-6 rounded-md bg-score-warning/10 text-score-warning flex items-center justify-center flex-shrink-0 mt-0.5 border border-score-warning/20">
            <Lightbulb className="w-3.5 h-3.5" />
          </div>
          <div>
            <h3 className="text-[11px] font-mono font-bold uppercase tracking-wider text-score-warning mb-0.5">
              What Hiring Managers See & The Fix:
            </h3>
            <p className="text-xs sm:text-sm text-text-secondary leading-relaxed font-sans">
              {explanation}
            </p>
          </div>
        </div>
      )}
    </Card>
  );
};
